### PR TITLE
OvrIntegration: Adapt to API changes in Oculus SDK 1.17.0

### PR DESCRIPTION
**Pull request by Squareys**
Hi @mosra !

Just came across this, this is not urgent, merge whenever you find the time.

Cheers, Jonathan

### CODE REVIEW

**Comment by mosra** [comment]
Thank you!

One problem I see immediately (maybe you remember): there was no easy way to get the latest SDK from Oculus website, so the CI is stuck on something very outdated. Any idea how to solve this (besides hosting it privately)?

**Comment by Squareys** [comment]
@mosra Yup, see last commit. I wonder if the access token expires sometime... otherwise we can refresh it and hope for the cache staying valid? :P

**Comment by Squareys** [comment]
Well, alright, it seems to download something else it seems...

**Comment by mosra** [comment]
Huh, this is still a thing? :D

**Comment by Squareys** [comment]
@mosra Yes, we didn't merge it, because we didn't manage to get the ovr sdk downloaded by the CI.

**Comment by Squareys** [comment]
Actually, now that I think of it, we wanted to try whether the download key expires somehow. Also, it looks like I need to add some lines to make it build the Debug libraries of the SDK.

**Comment by Squareys** [comment]
Summarizing offline discussions:

Solution to Oculus SDK not being automatically downloadable anymore is to host some minimal archive required for the build and use that. To generate it, I added a python script with 869ca71.
This is useful anyway, since LibOVR links static CRT by default and therefore is not compatible with all other magnum libraries (which link dynamic CRT by default) and we therefore need to patch the VS projects.

This will be merged once mosra finds the time after some important bigger changes in the main repository.

**Comment by mosra** [comment]
Random idea since I don't have time to set up `ci.magnum.graphics` yet (and won't have for the next x weeks): does the SDK provide some version define that could be used to make it temporarily work both with the currently still downloadable SDK and the latest one? Yes, it's ugly and all, but better than have this totally non-compilable with latest SDK -- I may have a need for a working version soon.

**Comment by Squareys** [comment]
>  it took me almost 12 months to merge

Better late than never 😆 Since nobody complained yet... :D

Thank you for merging! 🎉

**Pull request closed without merging**
